name: Publish to NPM Registry

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  check-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Check New Tag
        if: github.ref_type != 'tag'
        run: exit 0

  publish-npm:
    runs-on: ubuntu-latest
    needs: [check-tags]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
