name: Publish to NPM Registry

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    needs: [check-tags]
    steps:
      - name: Check New Tag
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
        if: github.ref_type == 'tag'
        run: yarn install --frozen-lockfile
        run: yarn build
        run: yarn test
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
